% ----------------------------------------------------------------------
% fxnConfig.m
%
% Configurations used in this pipeline
% Documenttaion of this pipeline
% ----------------------------------------------------------------------
% Notes: 
% -
% ----------------------------------------------------------------------
% Input(s) :
% -
% ----------------------------------------------------------------------
% Output(s):
% -
% ----------------------------------------------------------------------
% Function created by Rachel Chen (qc898@nyu.edu)
% Last update : 2026-03-02
% Last edited by : Rachel Chen
% Project : VR
% Version : 1.0

%clear; close all; clc;

%% ================= CONFIGURATIONS =================

% Experiment configurations
n_target = 9;
target_order = [7, 8, 9;
                4, 5, 6;
                1, 2, 3];

axis_names = {'X', 'Y', 'Z'};

% Plotting Colors
col_np    = [210, 210, 210] / 255;  % gray (No-penalty)
col_p_neg = [67, 112, 180] / 255;   % blue (Left penalty, e.g., negative)
col_p_pos = [195, 0, 120] / 255;    % magenta (Right penalty , e.g., positive)

ax_colors = [[41,157,143]./255;     % X - green?
            [233,196,106]./255;     % Y - yellow    
            [106, 92, 164]./255];   % Z - deep purple


% Path
%dataDir = fullfile(pwd, 'processedData','splitPenalty');



%% ================= PIPELINE STRUCTURE =================

% mainAna.m                                     ← Main analysis script
% ├── fxnConfig.m                               ← Global configurations 
% ├── [Model-Free]
% │   ├── analyze_targets_split.m               ← Unity data preprocessing
% │   ├── EP_3D.m                               ← 3D Visualization for emperial endpoints
% │   ├── xyz_projection_butterfly.m            ← Projecction to X/Y/Z axes
% │   └── mf_shiftAna_split.m                   ← Model-free stats
% └── [Model-Based]
%     ├── cov_from_reachingdata.m               ← Convariance matrix by conditions
%     ├── ideal_observer_1D.m                   ← 1D Ideal observer model
%     ├── project_to_optimal_shift_1D           ← Projection to 1D optimal shifts
%     ├── ideal_observer_3D.m                   ← 3D Ideal observer model
%     └── project_to_optimal_shift_3D           ← Projection to 3D optimal shifts


%% ================= DOCUMENTATIONS =================
% -------- Data proccessing --------
% analyze_targets_split.m
%       Data preprocessing, spliting data by 
%       penalty conditions (No-penalty/+penalty/-penalty)
%       Results used for model free analysis
%
% cov_from_reachingdata.m
%       Created by Luhe Li
%       Calcualting covariance matrices by conditions
%       Creating files used for Model-based analysis


% -------- Plotting function --------
% xyz_projection_butterfly.m
%       Plotting histogram of endpoints projection to x/y/z, splitting by
%       penalty conditions (No-penalty/+penalty/-penalty)
%
% EP_3D.m
%       3-panel subplot visualization per target (with penalty region shaded):
%           Left:   All 3 conditions (NP, P_NEG, P_POS)
%           Middle: NP + P_POS only
%           Right:  NP + P_NEG only
%
% xyz_projection_butterfly.m
%       Butterfly plot: Left penalty on bottom, Right penalty on top.
%           For each axis (X, Y, Z), one figure with 9 subplots (one per target).
%           Each subplot shows:
%               - No-Penalty condition (as reference)
%               - Penalty on left (blue, labeled as negative)
%               - Penalty on right (magenta, labeled as right)
% 
% project_to_optimal_shift_1D
%       Butterfly plot: Left penalty on bottom, Right penalty on top.
%           Projection to the optimal shift generated by 1D ideal observer model, one figure with 9 subplots (one per target).
%           Each subplot shows:
%               - No-Penalty condition (as reference)
%               - Penalty on left (blue, labeled as negative)
%               - Penalty on right (magenta, labeled as right)
% 
% project_to_optimal_shift_3D
%       Butterfly plot: Left penalty on bottom, Right penalty on top.
%           Projection to the optimal shift generated by 3D ideal observer model, one figure with 9 subplots (one per target).
%           Each subplot shows:
%               - No-Penalty condition (as reference)
%               - Penalty on left (blue, labeled as negative)
%               - Penalty on right (magenta, labeled as right)

% -------- Models --------
% ideal_observer_1D.m
% ideal_observer_3D.m


% -------- Stats --------
% mf_shiftAna_split.m
%       Aiming to answer:
%       1. Is the shift on each axis significantly 
%           different from 0? (one-sample t-test)
%       2. Does |shift| differ across X, Y, Z? (RM ANOVA + post-hoc)






%% ================= OTHERS =================

% -------- Some scripts that are abolished now --------
% -------- These files should only be in Rachel's local --------
%
% analyze_targets.m
%       Data preprocessing, spliting data by 
%       penalty conditions (No-penalty/Penalty)
%       Results used for model free analysis
% xyz_projection.m
%       Plotting histogram of endpoints projection to x/y/z
%       Only No-penalty v.s. Penalty
% EP_by_target_split.m
%       3D visualization of each targets by penalty conditions
%       (No-penalty/+penalty/-penalty)
%       Each target as a single figure
% EP_visualization_by_target.m
%       3D visualization of each targets by penalty conditions
%       (No-penalty/Penalty)
%       Each target as a single figure
